### ISSUE TITLE
리버전 비교에서 표시되는 버튼 문제

### ISSUE THREAD

**Issue by hellojo011** [LiteHell/NamuFix#1]
각각 버튼이

문서명?oldrev=125&rev=126"><-- r125 vs r126 
문서명?rev=126">r126 보기 
문서명?from=127">역사로 
문서명?rev=127">r127 보기 
문서명?oldrev=127&rev=128">r127 vs r128 -->

로 표시되고 링크도 재대로 걸리지 않습니다. 확인 부탁드립니다.

**Comment by hellojo011** [comment]
Vivaldi 1.14.1077.41 / 모바일 파이어폭스 58.0.1 Tampermonkey 기준입니다.

**Comment by LiteHell** [comment]
그럼 그냥 간단하게 롤백하죠 뭐
