### ISSUE TITLE
Firefox에서 NaumFix가 작동하지 않습니다.

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#102]
Firefox에서 Tampermonkey를 이용하여 설치해도, Greasemonkey를 이용하여 설치해도 NamuFix가 작동하지 않습니다.
PC(Windows 10 Pro Insider Preview) 환경과 모바일(Android 7.0) 환경 모두 작동하지 않습니다.

**Comment by pseol2190** [comment]
여전히 같은 현상입니다만...

**Comment by LiteHell** [comment]
재설치해보세요.
