### ISSUE TITLE
설정위치 버그

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#104]
# 설명
관리자인데, 일괄 차단 등의 메뉴가 기존의 '특수 기능' 탭이 아닌 사용자 탭에 들어가 있습니다. 확인 부탁드립니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Vivaldi 1.16
 * 사용하는 유저스크립트 매니저 : Tampermonkey

![a90ad744-e64a-4257-b94b-f078c6a4dabd](https://user-images.githubusercontent.com/36038285/42125584-e1c98ab8-7cb4-11e8-88a7-8e8ae4dde4c0.png)

**Comment by LiteHell** [comment]
버그가 아닙니다. 특수기능 탭에 들어가 있는 것이 버그입니다.

**Comment by pb1112** [comment]
그런건가요? 지금까지 관리자 하면서 항상 특수기능 탭에서 이용해 왔는데 그게 오히려 버그였군요.

**Comment by LiteHell** [comment]
로그아웃하시면 그게 라이브 메뉴로 갑니다. 그래서 버그입니다.

**Comment by LiteHell** [comment]
아니었던가? 아무튼 사용자 메뉴에 들어가는 게 정상입니다.
