### ISSUE TITLE
[철회] 업데이트 후에도 '새 버전 설치' 창이 표시됩니다.

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#108]
# 설명
ㅈㄱㄴ + 혹시 버전 수정을 까먹으신 건가요?
# 이용환경
* 운영체제 : Android 7.0
* 브라우저 : 불여우
* 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by pseol2190** [comment]
죄송합니다. 제 디바이스에서 'Update' 버튼이 잘 눌리지 않은 것으로 보입니다. 정상적으로 작동하는 것을 확인하였습니다. 그냥 닫아주세요.

**Comment by Hoto-Cocoa** [comment]
본인이 닫으실 수 있습니다.

**Comment by pseol2190** [comment]
@Hoto-Cocoa 닫았습니다.
