### ISSUE TITLE
차단기록 조회, 일괄차단이 되지 않습니다.

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#109]
# 설명
차단기록 조회, 일괄차단이 되지 않습니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Vivaldi
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by pb1112** [comment]
아 서버 문제가 아니라 버그였군요

**Comment by e080hsm** [comment]
저도 같은 증상을 겪고 있습니다. 윈도 8.1 크롬 67.0.3396.99(공식 빌드) (64비트) 템퍼몽키

**Comment by pb1112** [comment]
구버전으로 되돌려도 조회, 일괄차단 등이 안되는거 보니 상당한 버그인가보네요.

**Comment by LiteHell** [comment]
저도 안 됐었는데 갑자기 잘 되네요. 왜지?

**Comment by LiteHell** [comment]
문제 재발시 다시 이슈 열어주세요.

**Comment by pb1112** [comment]
아직 안됩니다. 다시 이슈 열었습니다.

**Comment by wodud98** [comment]
서버 맛가면 그런거같던데 서버 이슈 아니였나요?
