### ISSUE TITLE
아직 안됩니다

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#111]
# 설명
IP유저 차단기록 및 국가, VPNGATE 조회 / 일괄차단 메뉴 작동하지 않습니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Vivaldi 1.16
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by LiteHell** [comment]
180826.0에서 해결됨.
