### ISSUE TITLE
Add support for theseed-skin-vector

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#112]
Would you like to make NamuFix to support [Vector](https://github.com/LiteHell/theseed-skin-vector) skin?

**Comment by 2DU** [comment]
어지간하면 한글로 하십셔

**Comment by pseol2190** [comment]
@2DU ''Declined, further messages like that will be ignored.''

**Comment by 2DU** [comment]
@pseol2190 예 안녕히가십셔
