### ISSUE TITLE
[Re] Add support for theseed-skin-vector

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#114]
_Note: This issue is a vandalism-recovered version of #112_
Please add support for [theseed-skin-vector](https://github.com/LiteHell/theseed-skin-vector).

**Comment by Hoto-Cocoa** [comment]
123test

**Comment by Hoto-Cocoa** [comment]
콜라보레이터분이 닫으신건데 딱히 반달로는 보이지 않습니다.

**Comment by 2DU** [comment]
어지간하면 한글로 하시죠

**Comment by pseol2190** [comment]
@2DU #26 #25 #12 #10 #9 #8 #7 #6 #3

**Comment by pseol2190** [comment]
Currently no plan to open issues in Korean.

**Comment by 2DU** [comment]
@pseol2190 아예 수고하셨구요 어지간하면 한글로 쓰시죠

**Comment by Hoto-Cocoa** [comment]
그 정 반대의 자세로 하는거 받아주는건 보통은 자신의 부모님밖에 없어요... 다른 곳에선 내쫓는다 이 말입니다...

**Comment by pseol2190** [comment]
@2DU
```I currently have no plan to open issues in Korean if you try to force me to do that. Trying to force me will result in completely opposite situlation.```
한번 더 이야기합니다. 당신이 강요하는 한 한국어로 이슈를 생성할 계획은 없습니다. 강요가 계속될 경우 오히려 정반대의 상황을 초래할 수 있습니다.

**Comment by pseol2190** [comment]
_Note: I will recover this issue immediately if you vandalize it as you did on #112._

**Comment by Hoto-Cocoa** [comment]
그러다 차단 당하시겠네요. 대놓고 콜라보레이터(나아가 레포 소유자)의 말을 씹겠다고 선언한건데, 잘 넘어가 질 것 같진 않네요.

**Comment by pseol2190** [comment]
그럼 위에 태그해 놓은 영어로 적혀 있는 이슈들은 뭡니까?

**Comment by pseol2190** [comment]
@Hoto-Cocoa 잘 알겠습니다. 다만 저분이 강요한다는 이유만으로 한국어로 새 이슈를 생성할 계획은 없음을 알려드립니다.
사실 과도한 분쟁과 싸움을 막기 위해서 일부 상황에서 영어로 이슈를 생성한 것입니다.
물론 다른 사용자가 영어를 모를 것이라고 생각해서가 절대로 아닙니다. 영어로 이슈를 작성하다 보면 한번 더 생각하고 쓰게 되지 않을까... 싶어서 그런 것입니다.

**Comment by Hoto-Cocoa** [comment]
영어로 분쟁을 막는다라... 당장 이 이슈만 보셔도 알 수 있으시겠지만, 어차피 달리는건 한글이라서요.

**Comment by pseol2190** [comment]
분쟁을 '직접적으로' 막기보다는 그냥 '한번 더 생각하고 쓰는 용도'에 가까운 것 같네요.

**Comment by pectussolentis** [comment]
DO NOT HARASS HIM. PLEASE.

**Comment by Hoto-Cocoa** [comment]
읽는데에 생각을 한번 더 하겠죠. 쓰는게 아니라요. 그리고 지금 당신의 문제점은 정식 콜라보레이터의 요구사항을 무시하고 이를 반달리즘이라고 한 뒤 무시하겠다고 하며 똑같은 행위를 반복하는겁니다. 평소에 좋아하시던 위키로 설명해볼까요? 이와 같은 행위는 나무위키에서 일반 문의 열은게 관리자에 의해 닫혔다고 반달리즘이라고 하며 동일 문의를 다시 열고 난 umanle이 부정적으로 보지 않는 한 닫아도 이를 계속 반달리즘으로 칭하고 다시 열겠다, 이 말이 되는겁니다.

**Comment by Hoto-Cocoa** [comment]
당연히 이러면 운영방해로 차단되겠죠.

**Comment by Hoto-Cocoa** [comment]
이런 행동은 나무픽스, 나아가 깃허브 커뮤니티를 발전 시키는 것에 악영향을 끼칩니다.

**Comment by Hoto-Cocoa** [comment]
듣기 싫은 말이라고 차단하는게 아니라, 모두가 비슷한 말을 하면 한번이라도 생각해보시는게 좋을 것 같네요.

**Comment by pseol2190** [comment]
어쨌든 강요를 받아들일 생각은 없음을 다시 한 번 알려드립니다.

**Comment by Hoto-Cocoa** [comment]
지난번에 리브레 위키에서 개발자 계정으로 만우절 이벤트(당시 당신은 이를 반달이라고 하며 신고를 했죠) 이후에 해당 계정을 탈퇴처리하고 달라지겠다며 닉변을 하셨는데 이렇게 되면 더하면 더했지 덜한 사람이 되진 않습니다.

**Comment by Hoto-Cocoa** [comment]
"나는 맞고 너는 틀렸어"라는 논리보다는 다른 사람의 의견을 수용 할 줄 아는 사람이 되시길 바랍니다.

**Comment by pseol2190** [comment]
어쨌든 위와 같은 강요를 받아들일 생각은 없음을 알려드립니다.

**Comment by 2DU** [comment]
안녕히가십셔
