### ISSUE TITLE
[Forwarded] 일괄차단 문제

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#115]
_Note: This issue is forwarded from [this post](http://gall.dcinside.com/dcwiki/427086)._
NamuFix에서 차단을 누르면 무한 처리중 메시지가 출력되는 문제가 있다고 합니다.

**Comment by pseol2190** [comment]
Accidentally closed by mistake, reopened.

**Comment by LiteHell** [comment]
180826.0에서 해결됨.
