### ISSUE TITLE
표 생성기 버그

### ISSUE THREAD

**Issue by kiwitreekor** [LiteHell/NamuFix#116]
표 생성기에서 칸에 아무 내용도 없었을 때 정말로 아무 내용도 넣지 않으면 colspan 문법이랑 충돌해서 한 칸으로 합쳐져 나타납니다. 생성기가 빈 칸에는 공백을 넣는 등의 조치가 필요할 듯.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Firefox 61.0.1
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : -

**Comment by LiteHell** [comment]
180826.0에서 해결됨.
