### ISSUE TITLE
게시판에서 작동하지 않습니다.

### ISSUE THREAD

**Issue by AQuickBrownFxJumpsOverTheLazyGod** [LiteHell/NamuFix#117]
# 설명
항상 잘 사용하고 있습니다. 감사드립니다.
일괄 차단은 뜨는데(테스트는 해 보지 않았습니다.), 게시판 시간대 변경이나 상용구 기능이 현재 작동하지 않는 것 같습니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Chrome 68.0.3440.106
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : 없음

**Comment by LiteHell** [comment]
@AQuickBrownFxJumpsOverTheLazyGod 빠른 시간내에 확인해보겠습니다.

**Comment by LiteHell** [comment]
180902.0 버전에서 수정함.
