### ISSUE TITLE
알파위키 게시판 지원 요청

### ISSUE THREAD

**Issue by BunnyMearcat** [LiteHell/NamuFix#119]
# 설명
[[https://board.alphawiki.org]] 베타테스트 후 정식으로 편입될 알파위키의 새 게시판입니다. 나무위키 게시판처럼 지원 요청합니다.

# 이용환경
 * 운영체제 : (K)ubuntu 18.04 LTS
 * 브라우저 : Firefox Developer Edition 63.0b2
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by pseol2190** [comment]
- [ ] 게시판 일괄 차단
- [ ] 상용구
- [ ] 게시판 시간대를 사용자 웹 브라우저의 시간대로 변경
