### ISSUE TITLE
Block ads on Namuwiki

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#120]
[As you know, Namuwiki recently added some advertisements on their web pages.](https://board.namu.wiki/free/1175741)
So I want you to add a feature to block them. Thank you.

**Comment by Hoto-Cocoa** [comment]
AdBlock Extension을 쓰시기 바랍니다.

**Comment by Emily23805** [comment]
@pseol2190 굿이 영어쓸려하지마셈 ㅋㅋㅋㅋ

**Comment by Hoto-Cocoa** [comment]
굿이...

**Comment by pseol2190** [comment]
@Emily23805 
+추가로 무기한 차단하겠습니다. 다시는 제가 열은 이슈에 오실 생각하지 마십시오.

**Comment by pseol2190** [comment]
아니 말을 쳐 해봐요 그따위로 말해놓고 튀지말고

**Comment by Katinor** [comment]
@pseol2190 님이 뭔데 다른사람 레포에서 남들보고 이슈에 말 하라말라 합니까? 무례합니다.

**Comment by pseol2190** [comment]
@Katinor 죄송합니다.

**Comment by Hoto-Cocoa** [comment]
타인의 레포인데 다른 사람이 이슈에 오는걸 당신이 뭔데 이래라 저래라 명령입니까? 당신부터 명령하지 마세요. 다른 사람의 말도 좀 수용할 줄 아는 사람이 되십시오.

**Comment by Tenpower** [comment]
싸우지들 마세요.

**Comment by pseol2190** [comment]
@Hoto-Cocoa @Tenpower
죄송합니다. 제가 이렇게 또 한번의 일을 일으키고 말았네요... 더 이상의 분쟁은 저 또한 원하지 않습니다.

**Comment by Katinor** [comment]
@pseol2190 충분히 알아들으셨을거라 봅니다. 여러분도 괜히 여러번 말하지마세요. 깃헙 이슈공간은 싸우려고 있는곳이 아닙니다.
