### ISSUE TITLE
아카이브 링크 수정요청

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/NamuFix#121]
제가보기엔 아카이브는 현재 phpgongbu.ga로 되어있습니다. 이번에 깔끔해진 namuwiki.ml로하시는게 어떠신지요? 감사합니다.

**Comment by Tenpower** [comment]
뭐지? 닫은적이 없는데

**Comment by LiteHell** [comment]
설정에서 아카이브 사이트를 선택할 수 있도록 개선할 예정.
