### ISSUE TITLE
Request to decline #121

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#122]
_Since I cannot reply to #121 (it says "You can't perform this action at this time."), I opened a separated issue._
@Tenpower requested to change primary archival service for NamuFix from https://phpgongbu.ga/archive/ to https://namuwiki.ml/archive/, but I'm here to **strongly** oppose and request to decline and close it immediately.

**Comment by pseol2190** [comment]
I think there's no reason to change it, and he said _"이번에 깔끔해진 (Recently been neat)"_, but there's no reason to say https://namuwiki.ml/archive/ is really neat.

**Comment by Hoto-Cocoa** [comment]
이거 그냥 #121에 적으시는게 LiteHell님한테도 이슈 관리에 편하실겁니다.

**Comment by Hoto-Cocoa** [comment]
#121 에 답글을 하실 수 없다 적으셨는데... 그건 Tenpower님이 그쪽을 차단했던 한 것 같네요.

**Comment by pseol2190** [comment]
@Hoto-Cocoa
![Cannot reply to that](https://user-images.githubusercontent.com/39310079/45589971-f94bd000-b969-11e8-993e-e26143601014.PNG)

**Comment by Hoto-Cocoa** [comment]
"즉각적으로" 이런 단어를 사용하면 명령조로 보이기 쉽습니다. 그냥 "#121에 글을 적을 수 없어서 새로운 이슈를 개설하여 참여합니다. 저는 바꿀 이유가 없다고 생각합니다. 개설하신 분은 namuwiki.ml이 더 깔끔하다고 하셨는데 딱히 그런 것 같지 않기 때문입니다." 라고 적으시면 되고요, 굳이 한국인이 한국어로 관리하고 한국인만이 사용하는 것을 예상하고 만든 레포에 한국인이 영어로 이슈를 열 필요는 없습니다. 이럴 경우에는 한국어로 이슈를 여는게 모두를 위한 길이죠.

**Comment by Hoto-Cocoa** [comment]
저는 차단되도 저렇게는 안뜨던데 저렇게 뜨는건 뭔지 잘 모르겠네요. 한번 찾아보심이?

**Comment by Tenpower** [comment]
깃헙 하면서 이런 경우는 처음보네요.
