### ISSUE TITLE
NamuFix window layout broken on Microsoft Edge

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/NamuFix#124]
NamuFix window doesn't show correctly in pages on [Namuwiki](https://namu.wiki/) (senkawa skin):
![image](https://user-images.githubusercontent.com/43488966/45919860-2b63b180-bed7-11e8-8837-f70774c67b15.png)
Except special pages and discussions:
![image](https://user-images.githubusercontent.com/43488966/45919887-8a292b00-bed7-11e8-9f5b-98e6446905f4.png)
![image](https://user-images.githubusercontent.com/43488966/45919907-ff94fb80-bed7-11e8-9265-adf9576d6cbe.png)

**Comment by LiteHell** [comment]
Try again

**Comment by LiteHell** [comment]
be patient until fixed.
