### ISSUE TITLE
기능 추가 요청입니다.

### ISSUE THREAD

**Issue by AQuickBrownFxJumpsOverTheLazyGod** [LiteHell/NamuFix#130]
혹시 이게 구현이 가능할지는 모르겠는데,
https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test
위 사이트의 검색 결과를 IP 기여 목록 창이랑 토론 주소 조회 창 옆에 나타나게 할 수 있을까요?

어렵다면 안해주셔도 됩니다.

감사합니다 :)

**Comment by LiteHell** [comment]
프록시여부만 있으면 되나요?

**Comment by LiteHell** [comment]
190120.0에서 추가됨.
