### ISSUE TITLE
엣지 일괄차단 기능

### ISSUE THREAD

**Issue by AQuickBrownFxJumpsOverTheLazyGod** [LiteHell/NamuFix#132]
# 설명
안녕하세요. 엣지 브라우저에서 일괄 차단 기능이 작동하지 않습니다. 확인 부탁드립니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : MS edge 42.17134.1.0
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by LiteHell** [comment]
@AQuickBrownFxJumpsOverTheLazyGod 추후 확인하겠습니다.

**Comment by LiteHell** [comment]
잘 되는데요? 어떨때 잘 안되는지 자세하게 설명 부탁드립니다.
