### ISSUE TITLE
사파리에서 빠른차단 기능이 작동하지 않습니다.  

### ISSUE THREAD

**Issue by boki726** [LiteHell/NamuFix#133]
# 설명
아이피나 아이디의 기여 내역에 들어가면 나오는 빠른 차단 기능이 작동하지 않습니다. 

# 이용환경
 * 운영체제 : MacOS Mojave
 * 브라우저 : Safari 12.0.3 (14606.4.5)
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : 없음

**Comment by LiteHell** [comment]
@boki726 시간이 나는대로 해결하겠습니다.

**Comment by boki726** [comment]
수고 많으십니다. 감사합니다.
