### ISSUE TITLE
빠른차단이 되지 않습니다

### ISSUE THREAD

**Issue by kmj3614824** [LiteHell/NamuFix#134]
# 설명
사용자계정에서나 ip에서 빠른차단이 되지 않습니다

# 이용환경
 * 운영체제 : Windows 10 
 * 브라우저 : Chrome 72.0.3626.109
 * 사용하는 유저스크립트 매니저 : Tampermonkey 
 * 함께 이용하는 확장 : 나무위키에서 동작하는 유저스크립트나 확장을 이용하신다면 써주세요. (권장)

**Comment by zlzleking** [comment]
@kmj3614824 차단 시스템 api 문서를 주세요

**Comment by LiteHell** [comment]
나무픽스 설정은 확인하셨나요?

**Comment by AQuickBrownFxJumpsOverTheLazyGod** [comment]
나무픽스 상 모든 차단 기능이 작동하지 않습니다.

**Comment by zlzleking** [comment]
차단 시스템 api 문서를 주세요
