### ISSUE TITLE
스레딕 헬퍼 자신의 퍼스널 컬러 설정 건의.

### ISSUE THREAD

**Issue by MyDimLight** [LiteHell/NamuFix#136]
# 설명
토론 아이덴티콘, 스레딕 헬퍼 방식에서 자신의 퍼스널 컬러를 지정하고. 다른 사람들이 볼 수 있게 하시면 좋을거 같습니다. 설정을 안한 사람들은 랜덤으로 돌리고요.

# 이용환경
 * 운영체제 : Windows 10 Home 64bit
 * 브라우저 : Chrome 74.0.3729.131
 * 사용하는 유저스크립트 매니저 : Tampermonkey 
 * 함께 이용하는 확장 : uBlock Plus Adblocker, 나무위키 게시판 자동 로그인 스크립트

**Comment by LiteHell** [comment]
다른 사람의 랜덤 컬러가 자신의 퍼스널 컬러랑 동일할 수도 있어서, 생각을 좀 해봐야 될 것 같습니다.
null

**Comment by MyDimLight** [comment]
색상코드로 지정하면 되지 않을까 싶습니다.

**Comment by MyDimLight** [comment]
색상코드로 지정을 하면 중복률이 낮지 않을까 싶습니다. 지금 랜덤으로 부여되는 색상도 중복이 많아서 알아보기 어렵습니다.

**Comment by LiteHell** [comment]
일단 고려해보겠습니다.
null

**Comment by MyDimLight** [comment]
예 알겠습니다.

**Comment by LiteHell** [comment]
곰곰히 생각해봤는데 들일 노력에 비해 얻을 이득이 작을 것 같습니다.
