### ISSUE TITLE
나무픽스의 토론 도구문의

### ISSUE THREAD

**Issue by aeoab** [LiteHell/NamuFix#137]
# 설명
토론 도구 에서 "글씨 작게" 를 눌렀는데 {{{-1}}}: 가 아닌 {{{+1}}} 가 나왔습니다. 즉 글씨 크게와 동일하게 출력됩니다.
# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 :  74.0.3729.169(공식 빌드) (64비트)
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : x

항상 감사합니다!

**Comment by LiteHell** [comment]
190605.0에서 해결

**Comment by aeoab** [comment]
고생 많으셨어요.. 항상 감사드립니다!
