### ISSUE TITLE
기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by JJO99** [LiteHell/NamuFix#138]
# 설명
나무위키에서 나무픽스 잘 사용중입니다. 
혹시 게시판에서 글 작성자나 댓글 작성자의 아이피/아이디를 클릭하면 자동으로 나무위키의 기여내역으로 넘어갈 수 있는 기능을 추가해주실 수 있나요?

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Chrome 75
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by LiteHell** [comment]
190625.0에서 추가됨.
