### ISSUE TITLE
편집요청 페이지에도 빠른차단 버튼 추가

### ISSUE THREAD

**Issue by JJO99** [LiteHell/NamuFix#139]
# 설명
변경내역, 토론, 기여내역 페이지에서 [차단] 버튼으로 빠르게 차단이 가능한데, 편집 요청 페이지에서도 [빠른 차단]과 같은 버튼을 만들어 빠르게 아이피 및 편집요청 링크 첨부해 차단이 가능할지 문의합니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Chrome 75
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by LiteHell** [comment]
190706.0 버전에서 추가함.
