### ISSUE TITLE
편집 요청 일괄 닫기

### ISSUE THREAD

**Issue by qlrhdro92** [LiteHell/NamuFix#140]
# 설명
최근 나무픽스를 알게 되고 업무를 정말 편하게 처리하고 있습니다. 다만 반달러가 편집 요청 기능을 이용하여 도배를 할 경우, 하나하나 닫아야 하기에 시간이 오래 걸리고, 그 사이에 반달러가 또 다시 반달을 하면 편집 요청이 도배된 상태로 남아 있게 됩니다. 편집 요청 일괄 닫기 기능을 만들어 주시면 감사드리겠습니다. (편집 요청 옆에 체크박스를 추가한 뒤 일괄 닫기 버튼을 추가하는 것이 좋아 보입니다.)

**Comment by JJO99** [comment]
안그래도 올려볼까 했는데 올려주셨군요
어차피 편집요청은 번호 순서대로 올라가니까 (시작 번호)와 (끝 번호)를 입력해 해당 번호들을 일괄 닫기 할 수 있도록 만들어도 괜찮지 않을까 제안해봅니다.

**Comment by LiteHell** [comment]
기여목록에 해당 기능을 추가하면 될까요?

**Comment by JJO99** [comment]
이슈 여신분은 최근 토론 내역 페이지에서 편집 요청 옆에 체크박스를 만들어 바로 삭제할 수 있게 하는걸 원하시는듯 하고
저는 위치 상관이 없습니다.

**Comment by qlrhdro92** [comment]
그것도 괜찮아 보입니다. 빠른 처리가 가능할 것 같습니다.

**Comment by Nk431** [comment]
나무픽스의 메뉴에 특정 아이피를 입력 후 확인을 누르면 해당 아이피의 편집요청은 모두 일괄적으로 닫히는 기능이면 좋겠네요.

**Comment by LiteHell** [comment]
생각해봤는데 빠른 차단 팝업에 편집 요청 닫기 버튼을 만드는 방안은 어떤가요?

**Comment by LiteHell** [comment]
아 편집요청은 기여목록에 안 뜨네요... 최근 토론 내역에 표시하는 방안으로 갈 것 같습니다.

**Comment by LiteHell** [comment]
일단 생각해보겠습니다..

**Comment by LiteHell** [comment]
190727.0 버전에서 추가됨.
