### ISSUE TITLE
모바일 파이어폭스 나무위키 버그 개선. 

### ISSUE THREAD

**Issue by theboys507** [LiteHell/NamuFix#141]
# 설명
모바일에서는 편집 요청에서의 빠른차단이 안먹힙니다. 일반 pc버전에서는 잘먹히지만 유독 모바일에서는 반달성 편집 요청 처리할때 차단을 해도 차단이 안된걸로나옵니다. 해결방법 없나요?

# 이용환경
 * 운영체제 : Android (galaxy note 4)
 * 브라우저 : Firefox (mobile)
 * 사용하는 유저스크립트 매니저 Tampermonkey
 * 함께 이용하는 확장 : 나무위키에서 동작하는 유저스크립트나 확장을 이용하신다면 써주세요. (권장)

#버그

**Comment by LiteHell** [comment]
전 잘 되는데... 죄송하지만 더 자세히 설명해주실 수 있으신가요?
