### ISSUE TITLE
빠른 차단 기능에 버그가 존재합니다.

### ISSUE THREAD

**Issue by qlrhdro92** [LiteHell/NamuFix#142]
# 설명
현재 아이피, 사용자 기여 목록에서 차단을 하면 차단 사유에 원래 문서와는 완전히 다른 문서와 리비젼이 뜹니다.
![image](https://user-images.githubusercontent.com/48861312/61609526-60749800-ac91-11e9-81bd-50c4b7fab216.png)

**Comment by LiteHell** [comment]
190723.0에서 해결
