### ISSUE TITLE
the seed 업데이트 후 나무픽스 미작동

### ISSUE THREAD

**Issue by ghost** [LiteHell/NamuFix#144]
## 설명
the seed 업데이트 후 렌더러와 시스템, 디자인이 바뀌었는데 나무픽스가 동작하지 않습니다. 해결 부탁드립니다.

**Comment by yangis1019** [comment]
참고로 the seed의 렌더러는 vue.js로 바뀌었습니다. 이점 참고 바랍니다.

**Comment by LiteHell** [comment]
the seed engine의 렌더러가 vue.js(nuxt)로 바뀐다는 점은 매우 잘 알고 있습니다.
시간적, 자원적 여유가 나는대로 개발 시작할 예정입니다.

**Comment by PlavorSeol** [comment]
사실상 완전히 rewrite해야 하는 거 아닌가 싶은데요...
