### ISSUE TITLE
rawgit 주소 교체

### ISSUE THREAD

**Issue by Lastorder-DC** [LiteHell/NamuFix#145]
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.

Rawgit 서비스가 약 한달후 종료될 예정이므로 변경해야 합니다. 유사 서비스로는 https://raw.githack.com/ 이 있습니다.

**Comment by LiteHell** [comment]
3ad2d7324a42c7306b02541e3c16d7824e0e2930 커밋에서 해결됨.
