### ISSUE TITLE
IP 조회 관련

### ISSUE THREAD

**Issue by gdl-888** [LiteHell/NamuFix#148]
# 설명
위키 자체 문제인지는 모르겠으나 토론이랑 기여 목록에서 IP조회중만 계속 나오고, VPN 불러고기가 되지 않습니다. ipinfo.io를 KISA로 바꾸어도 작동하지 않습니다.

# 이용환경
 * 운영체제 : 윈도우 7 32-비트
 * 브라우저 : Firefox 74.0
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : 없음

**Comment by LiteHell** [comment]
잘 될겁니다.
