### ISSUE TITLE
일괄 화일올리기 오류 창 관련 개선 건의합니다.

### ISSUE THREAD

**Issue by gdl-blue** [LiteHell/NamuFix#149]
# 설명
일괄적으로 화일을 올린 후 오류 창("오류들이 발생했습니다")에 닫기 단추가 없어 닫기 위해 F12 도구를 사용하거나 새로고침을 해야하는 경우가 있습니다. 해당 창에 [닫기] 단추가 추가되었으면 합니다.

# 이용환경
 * 운영체제 : Windows 7 32-비트
 * 브라우저 : Firefox 74.0
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : https://github.com/gdl-888/userscript-SeedReverter

**Comment by LiteHell** [comment]
200327.0버전에서 해결
