### ISSUE TITLE
나무픽스로 인한 나무위키 작동 중단이 있습니다.

### ISSUE THREAD

**Issue by Qazapoko** [LiteHell/NamuFix#24]
안녕하세요. 평소 구글 크롬을 사용해서 나무픽스를 애용하고 있습니다. 그런데, 나무위키의 [스타크래프트/트리거](https://namu.wiki/w/%EC%8A%A4%ED%83%80%ED%81%AC%EB%9E%98%ED%94%84%ED%8A%B8/%ED%8A%B8%EB%A6%AC%EA%B1%B0) 부분을 편집하기 위해서 편집창을 띄울 때마다 몇 분간 컴퓨터가 느려지다가 편집창이 열리고 나서 크롬이 강제종료되는 현상이 관찰되었습니다. 혹시나 문서 자체의 문제인가 해서 나무픽스를 끄고 편집창을 띄웠더니 잘 되더라고요. 혹시 이 부분을 고쳐주실 수 있나요?

**Comment by LiteHell** [comment]
그 문서에서만 발생하는 버그인가요?

**Comment by Qazapoko** [comment]
살펴보니 다른 문서에서도 그러네요. 크롬 창을 강제종료 하기 전에 임의종료 하더라도 마찬가지 현상이 발생합니다.

**Comment by LiteHell** [comment]
스크립트와 관련된 오류창 같은게 뜨나요?

**Comment by Qazapoko** [comment]
그런 건 뜨지 않고, 단순히 종료되기 전에는 응답없는 페이지 창이 뜨고, 종료되고 난 후에는 기존 탭 복구에 대한 창과 뜹니다.

**Comment by LiteHell** [comment]
혹시 Tampermonkey를 이용하지 않고 설치했나요?

**Comment by Qazapoko** [comment]
Tampermonkey를 이용해서 설치했습니다. 그리고 이제보니 크롬에서 문제가 되는 나무위키 창을 종료하더라도 크롬 자체가 프로세스에서 사라지기 전까지는 계속해서 컴퓨터에 부하를 야기합니다. 또 크롬을 다시 껐다가 켜지 않은 상태로 나무위키 창을 열면 Tampermonkey 아이콘이 사라져 있습니다.

**Comment by LiteHell** [comment]
어느 버전부터 그 현상이 발생되나요?

**Comment by Qazapoko** [comment]
가장 최신의 버전에서만 그 증상이 발생합니다.

**Comment by Qazapoko** [comment]
혹시 언제쯤 버그를 고친 버전이 나올 수 있나요? 궁금해서 여쭤봅니다.

**Comment by LiteHell** [comment]
제 컴퓨터에서는 님이 말씀하신 버그가 안타나타서 좀 힘들 거 같습니다.

**Comment by Qazapoko** [comment]
고생이 많으십니다. 감사합니다! 앞으로도 LiteHell님 믿고 나무픽스 애용할게요.

**Comment by LiteHell** [comment]
죄송하지만 혹시 완전하게 재설치를 해도 오류가 나타나나요?

**Comment by Qazapoko** [comment]
잘 작동이 되네요! 늦게서야 대답을 드리게 되어서 죄송합니다. 앞으로도 나무픽스 잘 쓰겠습니다.
