### ISSUE TITLE
레이아웃 개편 이후 토론에서 나무픽스 사용시 렉이 걸립니다.

### ISSUE THREAD

**Issue by man01** [LiteHell/NamuFix#29]
사용 브라우저는 구글 크롬이며, cpu는 인텔 코어 i3-4005u, 램 용량은 4기가바이트인 중저사양 환경입니다. 현재 증상은 다음과 같습니다.
1.댓글이 많은 토론일 경우 스크롤이 버벅거림
2.토론 댓글 입력이 버벅임. 키보드보안 액티브엑스를 생각하면 됨.

이 두가지 이며, 신속한 해결을 바랍니다.

**Comment by fromthere** [comment]
https://github.com/LiteHell/NamuFix/blob/master/NamuFix.user.js#L2201
https://github.com/LiteHell/NamuFix/blob/master/NamuFix.user.js#L2211
위 두 줄(NamuFix.user.js 파일의 2201번째 줄, 2211번째 줄입니다)의 200을 2000으로 바꾸시면 됩니다.
다만 새로 달리는 댓글은 처리가 조금 늦어질 수 있습니다.

자그마치 200ms마다 처리를 하도록 되어 있으므로 1초당 5번씩 실행되므로 현 구조상 매우 느려질수밖에 없습니다. 이외에도 전체적으로 타임아웃이 지나치게 짧게 되어 있습니다.

**Comment by LiteHell** [comment]
160109.0 버전에서 해결했으나 확실하진 않음. 오류가 안고쳐졌다면 해당 이슈 다시 열어주기 바람.

**Comment by man01** [comment]
늦게나마 답변 올리지만, 해결되었습니다. 이제 토론에서도 잘 작동 됩니다. 감사합니다.
