### ISSUE TITLE
임거와 관련된 기능 삭제 바랍니다.

### ISSUE THREAD

**Issue by man01** [LiteHell/NamuFix#30]
15년 10월 16일 부로 임거가 나무위키를 막아버렸습니다. 따라서 있으나 마나 하는 기능이 되었으므로 삭제 바랍니다.

**Comment by hellojo011** [comment]
첨언합니다. imgur 정책위반으로 현재는 미러에 폭탄을 돌린 상황인데, imgur 업로드 기능을 삭제하는 게 좋을 것 같습니다. 토론도 이미지를 자체 서버를 쓰는거로 결론이 나오고있으니

**Comment by LiteHell** [comment]
Completed on 151017.0 version.
