### ISSUE TITLE
리다이렉트가 증식합니다

### ISSUE THREAD

**Issue by Ahellina** [LiteHell/NamuFix#31]
![image](https://cloud.githubusercontent.com/assets/15073085/10556223/a53d888a-74b8-11e5-812c-cc10637fed0f.png)
편집을 누른뒤 뒤로를 누르면 하나씩 늘어나네요 역링크 토론 역사도 같은 현상이 발생합니다

**Comment by LiteHell** [comment]
@Ahellina 지금도 그러한 버그가 발생합니까?

**Comment by Ahellina** [comment]
해결되었습니다

**Comment by LiteHell** [comment]
그러면 이슈 닫겠습니다.
