### ISSUE TITLE
나무픽스 어떻게 삭제합니까?

### ISSUE THREAD

**Issue by anekanekanek** [LiteHell/NamuFix#32]
최근 들어서 이상한 문제가 자꾸 생깁니다. 나무픽스때문에 편집창이 극히 작아진다든지.. 그리즈멍키를 삭제했는데도 나무픽스는 지워지지 않다가 이제는 편집 버튼을 누르면 캠챠를 체크하라는데 정작 그 캡챠가 없는 등..

**Comment by LiteHell** [comment]
그리스멍키 지우면 같이 지워집니다. (파이어폭스 사용자라면)

**Comment by anekanekanek** [comment]
그리즈멍키가 아니라 템퍼멍키입니다. 전 크롬 씁니다. 둘이 헷갈렸어요

**Comment by LiteHell** [comment]
그러면 Tampermonkey를 지우면 됩니다.
