### ISSUE TITLE
페이지 하단에 추가되는 비트코인 기부 관련

### ISSUE THREAD

**Issue by ray4167** [LiteHell/NamuFix#33]
비트코인 기부 이미지가 imgur로 되있어서 이미지가 뜨지 않습니다.
덧붙여서, 가끔씩 이 기부 안내문이 여러개가 떠 있을 때가 있습니다.
조속한 해결 부탁드립니다.

**Comment by LiteHell** [comment]
fixed on commit 4a5219038949e20b8acfcebd32d7e6626c3fbc13.
