### ISSUE TITLE
맞춤법 검사기 추가

### ISSUE THREAD

**Issue by artschool** [LiteHell/NamuFix#35]
추가해주세요 아 태그는 내가 붙이는 게 아니구나 멍청하게 닫았네 ㅅㅂ

**Comment by LiteHell** [comment]
171106.0 버전에서 해결됨, 다만 나사가 좀 빠졌음.

**Comment by artschool** [comment]
오오오 저도 까맣게 잊고 있었는데 고마워요!!!!!

2017. 11. 16. 오후 6:24에 "LiteHell" <notifications@github.com>님이 작성:
