### ISSUE TITLE
나무위키 기부 QR코드 관련

### ISSUE THREAD

**Issue by ray4167** [LiteHell/NamuFix#36]
QR코드가 imgur 링크 //i.imgur.com/DDsEsTo.png로 되있어서 안뜨네요 수정 부탁드립니다.
![2016-01-18 15-16-37](https://cloud.githubusercontent.com/assets/15443589/12384550/88885418-bdf6-11e5-8e6d-53dc9231312c.png)

**Comment by LiteHell** [comment]
커밋 4040e384d3f3a8bba756d1ebc9b7d6fb77b112c6 에서 수정됨
