### ISSUE TITLE
편집창 크기 조절시 CCL 체크박스,저장 버튼들과 겹침

### ISSUE THREAD

**Issue by YJSoft** [LiteHell/NamuFix#37]
![resize_error](https://cloud.githubusercontent.com/assets/5893514/12529409/1410001c-c1f8-11e5-9fc1-79af3fd72fa9.PNG)
위와 같이 편집창과 저장 버튼등 인터페이스와 겹침 현상이 있습니다.

**Comment by LiteHell** [comment]
재현할 수 없습니다. 문제가 발생하는 브라우저 환경을 자새히 말씀드릴 수 있나요?

**Comment by YJSoft** [comment]
@LiteHell 수정된 것 같습니다.
