### ISSUE TITLE
현재 업데이트 배포에 오류가 있습니다.

### ISSUE THREAD

**Issue by hellojo011** [LiteHell/NamuFix#43]
현재 사용중인 버전 : 171019.0
현재 최신 버전 : undefined

undefined버전에서의 변경 사항
undefined

버전하고 변경사항 자체가 정의되지 않았다는 오류가 뜹니다. 이게 페이지를 이동할때마다 뜨네요

**Comment by LiteHell** [comment]
사용하시는 브라우저와 확장 프로그램 (Greasemonkey? Tampermonkey?)이 어떻게 되시나요?

**Comment by hellojo011** [comment]
크롬 - Tampermonkey
모바일 파이어폭스 - Tampermonkey
둘 다 같은 메시지 뜹니다.

**Comment by LiteHell** [comment]
죄송하지만, 다음 주소에 접속해서 보이는 모든 것을 여기에 복사해주실 수 있으십니까?

https://api.github.com/repos/LiteHell/NamuFix/releases/latest

**Comment by hellojo011** [comment]
{
  "message": "API rate limit exceeded for 222.102.133.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

**Comment by LiteHell** [comment]
곧 고칠께요. 잠시만 기다려주세요.

**Comment by hellojo011** [comment]
워우.... 저 메시지 보아하니 IP에 대해서 제한이 걸린거군요....

**Comment by LiteHell** [comment]
Tampermonkey에서 업데이트를 수행해서 정상적으로 작동하는 지 확인해줄 수 있으신가요?

**Comment by hellojo011** [comment]
[유저 스크립트 업데이트 확인] 을 눌러도 "업데이트가 발견되지 않았습니다." 만 표시되고 새로고침해도 지속되네요

**Comment by LiteHell** [comment]
잘못 말했네요, 재설치를 해주실 수 있으신가요?

**Comment by LiteHell** [comment]
지우실 필요는 없습니다.

**Comment by hellojo011** [comment]
재설치해도 현상 지속됩니다. IP라도 바꿔야될까요....

**Comment by LiteHell** [comment]
아뇨아뇨 그러실 필요 없어요, 잠시만 기다려주세요.

**Comment by hellojo011** [comment]
방금 해결됐습니다. 감사합니다.
