### ISSUE TITLE
음, 아직 불려오기 오타가 고쳐지지 않은것 같습니다.

### ISSUE THREAD

**Issue by username011010** [LiteHell/NamuFix#47]
한번 수정을 하신것 같기는 하지만

여전히 불려오기 -> 불러오기로 표기가 됩니다. 

과거버전의 코드인지는 모르겠지만 공개된 코드에도 '불려오기'로 표기되어 있습니다.

번거로우시겠지만 한번 더 확인해주시면 감사하겠습니다.

**Comment by LiteHell** [comment]
c518dfb3893ee37c8f7248f60f0e02605ab54380 커밋에서 수정했습니다. 제가 그때 이슈를 잘못 읽고 거꾸로 수정한 거 같네요.
추후 업데이트에 반영될 예정입니다.

**Comment by LiteHell** [comment]
171106.0 버전에서 해결됨.
