### ISSUE TITLE
정말 나사 빠진 맞춤법 검사기가 맞군요ㅎㅎ

### ISSUE THREAD

**Issue by username011010** [LiteHell/NamuFix#48]
위키문법을 하나하나 전부 검사해서 친절히 맞도록 표기해 주는군요ㅋ 

하이퍼링크도 어절단위로 파악해서 사전에 없으면 바로 오타로 뜨고요.

위키문법과 인터넷 주소는 예외처리가 필요할 것 같습니다.

**Comment by LiteHell** [comment]
http/https 하이퍼링크는 검사 결과에서 "외부고리"라는 단어로 치환해 검사해도록 수정했습니다. 위키문법은 왠만한 건 예외처리 되있을텐데....? 오류가 나는 부분을 말씀해주실 수 있으십니까?

**Comment by username011010** [comment]
피드백이 늦어 죄송합니다. 

https://imgur.com/a/YPzXg

보통 표 서식을 지정하는 문법에서 발생합니다. 
tablewidth와 tablealign 문법은 중간을 띄어쓰던 안쓰던 제대로 작동하지만, table bordercolor 같은경우는 뒷 부분이 붙어있어야만 동작하므로 검사대로 띄어쓰기를 넣으면 동작하지 않습니다. 첫 두 문법도 굳이 거를 필요가 없으니 예외처리를 넣는것이 좋을것 같습니다.
+'rowbgcolor' 도 'row bgcolor' 로 수정합니다.  

HEX컬러코드(HTML컬러코드)의  문제도 있습니다. 모든 컬러코드에 발생하는것은 아니지만 단어가 내포된 것으로 보이는 경우 수정하는것 같습니다. 컬러코드는 #XXXXXX 형식으로 #뒤에 6자리가 오니 이를 인식하여 예외로 보면 될것 같습니다. (아니면 #000000부터 #FFFFFF까지를 모두 등록하는 방법도 있고요...)
