### ISSUE TITLE
표만들기 기능 건의

### ISSUE THREAD

**Issue by kangdol** [LiteHell/NamuFix#49]
표를 만들때 ~x~인것을 ~*~도 되게끔 해주셨으면 합니다.  숫자키가 있는 키보드 사용중인데 매우 불편합니ㅏㄷ

**Comment by LiteHell** [comment]
커밋 e21a5671ede5a856e430bd8967ad89a5c2eb1624 에서 수정완료. 다음 업데이트때 반영될 예정이니 기다려주세요.

**Comment by LiteHell** [comment]
버전 171118.0에 반영됨.
