### ISSUE TITLE
그라비타 누르면 기여내역 점프기로 갈 수 있게 하는 기능

### ISSUE THREAD

**Issue by teojeoboja** [LiteHell/NamuFix#50]
https://phpgongbu.ga/tocont.php 나무위키 기여내역 점프기
https://phpgongbu.ga/tc_awiki.php A위키 기여내역 점프기

설정
어두운 화면으로
KISA WHOIS
NamuFix 이슈트래커
NamuFix 설정
''''기여내역 검색기''''
내 정보
내 사용자 문서
내 문서 기여 목록
내 토론 기여 목록
로그아웃

이런 식으로요

**Comment by teojeoboja** [comment]
저 점프기로 아이피 유저 기여내역 검색도 가능합니다.

**Comment by LiteHell** [comment]
저 기능 아이피도 되여... 제가 생각없이 기능을 만들진 않습니다.

**Comment by teojeoboja** [comment]
아 기여 네임스페이스였군요. 처음 알았네요. 감사합니다.

**Comment by LiteHell** [comment]
나무픽스 깔면 생기는 기능입니다. 이슈 닫을께여

**Comment by teojeoboja** [comment]
넵
