### ISSUE TITLE
리다이렉트 무한 루프 버그

### ISSUE THREAD

**Issue by hellojo011** [LiteHell/NamuFix#54]
편집 충돌이 발생하거나 이미 생성된 리다이렉트 문서로 문서를 생성하면

[오류!] 문서 내용이 같습니다.

하고 리다이렉트 문서 편집창으로 되돌아오는데 다시 저장을 시도하면서 계속 새로고침됩니다. 예외 처리 바랍니다.

**Comment by LiteHell** [comment]
Resolve on 171203.0
