### ISSUE TITLE
나무픽스가 곧바로 실행되지 않습니다.

### ISSUE THREAD

**Issue by rienriri** [LiteHell/NamuFix#63]
나무픽스 업데이트 이후 나무위키에 접속하였을 때 나무픽스가 곧바로 실행되지 않네요...
나무픽스가 실행된다고 해도 오래 기다려야 실행이 되는지라 다소 불편을 겪고 있습니다.

**Comment by teojeoboja** [comment]
알파위키에는 토론 중 차단 기능이 나타나지 않는 듯 합니다. 이것도 확인 부탁드려요

**Comment by teojeoboja** [comment]
아 따로 설정해야 하군요. 제 건은 해결 되었습니다.

**Comment by LiteHell** [comment]
빨리 해결하겠습니다.

**Comment by LiteHell** [comment]
설정을 초기화해도 문제가 계속되나요?

**Comment by Eeclipse** [comment]
저도 그러네요.. 설정 초기화 해도 여전히 그렇습니다.

**Comment by LiteHell** [comment]
그러면 전체적으로 그러한 증상이 나타나나요?

**Comment by Eeclipse** [comment]
이번 업데이트로 바로 로딩되네요.

**Comment by LiteHell** [comment]
문제 생기면 이슈 다시 열어주세요~
