### ISSUE TITLE
토론 내 IP 차단이 작동되지 않습니다.

### ISSUE THREAD

**Issue by hellojo011** [LiteHell/NamuFix#65]
"사용자 이름이 올바르지 않습니다."

라는 메시지가 표시되고 처리가 안 되네요. 픽스 부탁드립니다.

**Comment by LiteHell** [comment]
해당 버그가 발생하는 쓰레드를 알려주시면 감사하겠습니다.

**Comment by LiteHell** [comment]
아 버그 확인했습니다. 곧 고치겠습니다.

**Comment by LiteHell** [comment]
171222.2버전에서 해결 완료
