### ISSUE TITLE
리캡챠 인증이 무한반복으로 뜨는 문제가 있습니다.

### ISSUE THREAD

**Issue by hellojo011** [LiteHell/NamuFix#67]
방금 리캡챠 창이 무한대로 떠서 NamuFix를 끄고 새로고침 > 서버 요청 경고(서버에 많은 요청을 보내고 있습니다.)에서 리캡챠 수행 > 다시 NamuFix 스위치 ON 시켜서 해결했습니다. 이 문제는 해결이 어려운가요? (문제가 발생할 때 자동으로 로그아웃도 됐습니다.)

**Comment by LiteHell** [comment]
일단 "새 리버전 알림"기능을 비활성화해보세요. reCAPTCHA 문제 해결은 시도해보겠습니다.

**Comment by hellojo011** [comment]
넵 수고많으십니다. 엔진에서 구현하면 좋을 걸 나무픽스가 다 구현하네요.....

**Comment by LiteHell** [comment]
아 서버에 많은 요청 그거는 reCAPTCHA 한번만 수행하고 나머지는 마우스 광클해서 닫아도 무방할 겁니다.

**Comment by hellojo011** [comment]
박스를 누르기 직전마다 계속 팝업이 떠서 누르기가 좀 곤란했거든요... 일단 지금 당장은 나무픽스 끄고 직접 들어가서 인증하는 방식으로 해결했으나 모르시는 분은 저와 같은 상황에 당황하실까봐요

**Comment by rienriri** [comment]
이거 문의하려고 했더니 이미 하셨군요...

**Comment by hellojo011** [comment]
@rienriri 일단 저만 당한 건 아니네요
