### ISSUE TITLE
Firefox에서는 일괄 차단 기능이 지원되지 않나요?

### ISSUE THREAD

**Issue by rienriri** [LiteHell/NamuFix#69]
firefox에서는 일괄 차단 메뉴가 보이지 않네요...
그리고 업데이트 설치하려고 하면 스크립트 raw만 뜨고요.
보통은 chrome 브라우저를 이용해서 딱히 큰 문제는 없지만 모바일에서 firefox 사용할 때 다소 불편한 감이 있어서 문의합니다.

**Comment by hellojo011** [comment]
모바일 파이어폭스에서 Tampermonkey로 사용중입니다만 일괄차단 잘 됩니다.

**Comment by rienriri** [comment]
@hellojo011 파폭도 일괄차단이 잘 되는군요... 저는 모바일 파폭으로도, PC 파폭으로도 일괄차단이 안 되고 있습니다.

**Comment by LiteHell** [comment]
설정을 확인해보세요.

**Comment by rienriri** [comment]
앗 이제 되네요. 감사합니다~
