### ISSUE TITLE
토론창과 편집창에서 나무픽스 도구가 두개가 뜹니다.

### ISSUE THREAD

**Issue by teojeoboja** [LiteHell/NamuFix#70]
텍스트 편집 관련 도구가 두개가 뜨네요

**Comment by teojeoboja** [comment]
거의 모든 기능이 두배로 뜨는 버그네요

**Comment by LiteHell** [comment]
사용하는 브라우저 종류와 운영체제, 그리고 버그가 발생하는 주소를 알려주세요.

**Comment by teojeoboja** [comment]
윈도우 10에 크롬이고요. 그라비타 누르면 나오는 나무픽스 설정 창, 토론 및 편집의 나무픽스 도구, 최근 변경과 문서 역사에 있는 빠른 차단 기능 버튼, 아이피 유저의 기여내역에 뜨는 아이피 정보 창이 모두 두개로 보입니다.

**Comment by teojeoboja** [comment]
http://gall.dcinside.com/board/view/?id=dcwiki&no=416161 참고해주세요

**Comment by LiteHell** [comment]
GitHub 이슈트래커도 이미지 올릴 수 있습니다. 굳이 디시인사이드에 올리지 마세요.

**Comment by teojeoboja** [comment]
아 그렇네요. 감사합니다.

**Comment by LiteHell** [comment]
그리고 저는 파이어폭스를 써서 그런지 제 노트북에서는 버그가 재현되지 않네요. 나중에 시간날때 고치도록 하겠습니다.

**Comment by LiteHell** [comment]
아 아니면 혹시 [팀뷰어](https://www.teamviewer.com) 쓰십니까?

**Comment by teojeoboja** [comment]
팀뷰어 안 써요..

**Comment by LiteHell** [comment]
그럼 됐고. 나중에 차차 고치도록 하겠습니다.

**Comment by teojeoboja** [comment]
넵

**Comment by teojeoboja** [comment]
아 보니까 제가 나무픽스를 두개나 깔아서 그렇네요

**Comment by teojeoboja** [comment]
해결되었습니다. 감사합니다.
