### ISSUE TITLE
KISA WHOIS 기능 작동방식

### ISSUE THREAD

**Issue by Triple3T** [LiteHell/NamuFix#71]
조회할 IP주소를 입력하는 란에 아무것도 입력하지 않고
 * 확인을 누르면 그냥 조회 창이 뜨고 응답이 없으며 
 * 취소를 누르면 다음과 같은 에러 메시지를 출력합니다: ![image](https://user-images.githubusercontent.com/12747984/34650381-b62172d4-f403-11e7-9922-29c2a9095dd6.png) 

이를 방지하기 위해 아예 입력을 받을 때 간단한 유효성 검사를 하는 것은 어떤가요?

**Comment by LiteHell** [comment]
Fixed on 180108.0 version
