### ISSUE TITLE
새로운 기능 추가 요청합니다.

### ISSUE THREAD

**Issue by base6464** [LiteHell/NamuFix#72]
차단된 사용자의 사문에 틀이 뜨면서 나오는 차단사유를 링크로 확인할 수 있게 가능할까요?

**Comment by LiteHell** [comment]
커밋 476fb57ea9828f06bd9ef0af3d19c8faa45bf140 에서 반영됨. 별 문제 없다면 다음 업데이트에 반영될 것임.

**Comment by LiteHell** [comment]
Resolved on 180130.0
