### ISSUE TITLE
다수 이미지 업로드 시에 파일명을 원본 그대로 업로드 하는 옵션

### ISSUE THREAD

**Issue by tosnamu** [LiteHell/NamuFix#73]
이 필요합니다. ㅠㅠ

나무위키에 특정 온라인 게임 아이템 DB를 만드는데
거기에 필요한 이미지를 수백개 업로드 해야합니다.
방법을 찾은 게 나무픽스의 동시 업로드 기능인데 임의로 파일명 앞에 뭐가 붙어버리네요...
앞 붙게 가능할까요?

중간에 리캡차 해달라고 요청하는 걸 닫기 눌러 무시해버리면 제끼고 업로드 이어하던데
동일 파일명 문서 있으면 패스하고 업로드 진행한 뒤, 끝날 때 패스한 문서 목록 보여주면 좋을 거 같아요.

**Comment by LiteHell** [comment]
생각해보겠습니다.

**Comment by tosnamu** [comment]
오 이 시간에 피드백이.. 잘 좀 부탁드리겠습니다 ㅠㅠ  우선 이미지 작업은 제껴놓고 문서부터 완성해나가고 있어봐야겠네요. 빠른 피드백 감사합니다.

**Comment by LiteHell** [comment]
Resolved on 180130.0
