### ISSUE TITLE
IP 정보가 조회가 되지 않습니다.

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#76]
IP 관련 정보를 조회중입니다. 잠시만 기다려주세요.

이 상태로 계속 유지가 되고 있습니다. 아까 나무위키 터졌었다는데 그 영향 때문일까요?

**Comment by base6464** [comment]
그 이후로 일괄차단에서 vpn 불러오기도 안됩니다. 나무위키단에서 나무픽스 서버를 막은듯 싶네요

**Comment by LiteHell** [comment]
해결됨.
