### ISSUE TITLE
토론 아이덴티티콘 업데이트되었나요?

### ISSUE THREAD

**Issue by rienriri** [LiteHell/NamuFix#77]
토론 아이덴티티콘 색깔이 바뀐 것 같은 느낌이 드네요.
~~예전 색깔이 더 좋았는데 아쉽네요~~
혹시 아이덴티티콘 색깔을 사용자가 지정할 수 있게 할 수는 없나요?

**Comment by LiteHell** [comment]
180209.0버전에서 설정 추가했으며 예전 아이덴티콘은 stewardlords/identicon.js를 선택하면 됨.
