### ISSUE TITLE
아이덴티콘 라이브러리중 Gravatar 사용불가

### ISSUE THREAD

**Issue by Lastorder-DC** [LiteHell/NamuFix#78]
![image](https://user-images.githubusercontent.com/18280396/36019362-605c4756-0dc2-11e8-90fe-2b3c3ec2eb63.png)

`www.gravatar.com` -> `secure.gravatar.com`

**Comment by LiteHell** [comment]
Resolved on 6d9d410dfc9bded9e9ca5a2d49da043cc21c80cb
