### ISSUE TITLE
토론 아이덴티콘 설정 문의

### ISSUE THREAD

**Issue by rienriri** [LiteHell/NamuFix#79]
https://github.com/LiteHell/NamuFix/issues/77에서 아이덴티티콘 설정에 대해 문의했습니다.
사실 그 기능이 그닥 중요한 기능은 아닌 데다가 보통 대수롭지 않게 넘기는 부분이라 다소 귀찮게 느껴지셨을 수도 있는데도, 해당 기능을 개발해 주셔서 정말 감사합니다.
언급하신 방법대로 해도 색깔이 그대로라 자세히 보니 디시라이트 갤러콘 방식이 아닌 아이덴티콘 방식에서만 지원되는 기능이더군요.
죄송하지만 혹시 디시라이트 갤러콘도 예전 색깔 롤백 기능 개발이 가능한가요? 자꾸 비슷한 문의로 귀찮게 해서 죄송합니다...

**Comment by LiteHell** [comment]
갤러콘 방식 관련 코드는 수정된 적이 없습니다.

**Comment by rienriri** [comment]
제 기억으로는 차단 전까지만 해도 남색이었던 갤러콘이 복귀 후에는 분홍으로 바뀌어 있길래 문의했습니다만... 색 관련 코드가 수정된 적이 없었나요?

**Comment by LiteHell** [comment]
아 그건 버그입니다. 제보 감사합니다.

**Comment by LiteHell** [comment]
시간 나는대로 해결하겠습니다.

**Comment by rienriri** [comment]
~~쓸데없는 눈썰미가 버그를 찾아냈군요~~ 해결해 주셔서 감사합니다...!
