### ISSUE TITLE
VPNGATE IP를 전부다 인식하지 못하는 것 같습니다.

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#80]
나무픽스 제작하시느라 수고가 많습니다. 

최근에 VPNGATE 관련 처리를 하면서 보니까, VPNGATE IP임에도 VPNGATE IP라고 인식하지 못하는 경우가 종종 있습니다.

![1111](https://user-images.githubusercontent.com/36038285/36068258-51f75cf2-0f14-11e8-9324-1dbf6b8bc724.PNG)
![2222](https://user-images.githubusercontent.com/36038285/36068259-521fc4f8-0f14-11e8-8516-2a205aeab61f.PNG)

확인 부탁드리겠습니다.

**Comment by LiteHell** [comment]
vpngate ip를 조회할때 [vpngate.net에서 제공하는 csv api](http://www.vpngate.net/api/iphone/)를 이용하기에 일부 ip는 누락될 수 있습니다. 양해바랍니다.
