### ISSUE TITLE
알파위키에서 나무픽스

### ISSUE THREAD

**Issue by mola11111** [LiteHell/NamuFix#82]
아무것도 안 먹힙니다.
수정바랍니다.

**Comment by BunnyMearcat** [comment]
현재 알파위키의 도메인이 **www**.alphawiki.org인데 나무픽스 스크립트에선 그냥 alphawiki.org로 되어 있어 발생하는 문제로 보입니다.

**Comment by LiteHell** [comment]
시간이 없어요ㅠㅠ. 조금만 더 기다려주세요.

**Comment by BunnyMearcat** [comment]
chromium이랑 Firefox quantum에서 둘다 안되는거 보면 딱히 브라우저 문제는 아닌 것 같습니다.
