### ISSUE TITLE
확실히 나무위키가 나무픽스를 싫어하나 보네요

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#83]
나무픽스 덕분에 나무위키 관리 잘하고 있습니다.

근데 나무위키에서 나무픽스를 막으려 드는건가요? 지금도 아이피 조회가 되질 않네요.

확인 부탁드립니다.

**Comment by pb1112** [comment]
아 나무위키가 아니라 운영하시는 서버의 문제 인건가요?

**Comment by LiteHell** [comment]
나무픽스 서버를 재시작하여 해결함.
