### ISSUE TITLE
새 기능 제안(약간 이상적)

### ISSUE THREAD

**Issue by wodud98** [LiteHell/NamuFix#85]
최근 수정내역의 아이피를 N초마다 받아서,

VPN 분석하는 사이트 API로 보내서 VPN 이 true로 나오면

즉시 조치 가능하도록 하는 기능이 있었으면 좋겠습니다.

약간의 이상적인 얘기긴 합니다.

**Comment by LiteHell** [comment]
너무 이상적입니다...
