### ISSUE TITLE
빠른차단이 일반사용자한테도 보입니다

### ISSUE THREAD

**Issue by namufix** [LiteHell/NamuFix#88]
이게 어찌됀일 인가요 차단은 돼지 않습니다만.. 문제가 될것같군요

**Comment by LiteHell** [comment]
1. 관리자 권한을 확인하는 것은 번거롭습니다. (senkawa 스킨 미사용자를 고려해야 함.)
1. 일반사용자는 권한이 없기 때문에 문제될 일이 없습니다.

따라서 수정하지 않을 계획입니다.
