### ISSUE TITLE
일반유저용 설정 추가요청

### ISSUE THREAD

**Issue by base6464** [LiteHell/NamuFix#89]
관리자할때는 편하게 썻지만 지금은 차단기능은 필요하지않습니다.

설정에서 일반유저모드를 키면 차단버튼을 숨겨주는 기능을 추가해주시면 유용하게 쓰일것 같습니다.

차단말고는 다 좋은기능입니다. 항상 감사드립니다.

**Comment by Lastorder-DC** [comment]
#88 댓글중 발췌
1. 관리자 권한을 확인하는 것은 번거롭습니다. (senkawa 스킨 미사용자를 고려해야 함.)
1. 일반사용자는 권한이 없기 때문에 문제될 일이 없습니다.
따라서 수정하지 않을 계획입니다.

**Comment by LiteHell** [comment]
일반유저모드는 추가하지 않을 예정이지만, 추후 차단버튼을 숨기는 옵션을 추가할 예정.

**Comment by LiteHell** [comment]
180507.0 버전에서 해결됨.
