### ISSUE TITLE
버그 제보합니다.

### ISSUE THREAD

**Issue by rienriri** [LiteHell/NamuFix#90]
차단 내역 조회나 whois 기능이 제대로 작동되지 않고 있습니다.
또 1.XXX.XXX.XXX 같은 아이피나 5.XXX.XXX.XXX 같은 IP처럼 IP 첫 자리가 10 미만인 경우 긴급 차단 시 계정으로 취급되어 차단이 먹히지 않기 때문에, IPACL 창에 가서 문서명과 리버젼 번호를 외우거나 메모장을 켠 뒤 처리해야 하는 경우가 왕왕 있습니다.

**Comment by LiteHell** [comment]
시험기간이라.... 최대한 빨리 고칠 수 있게 노력해보겠습니다.

**Comment by rienriri** [comment]
앗 시험기간이시군요... 바쁘실 텐데 괜히 부담스럽게 한 게 아닌가 싶네요. 천천히 고쳐 주셔도 감사하죠.

**Comment by LiteHell** [comment]
일단 서버이슈(whois 미작동 및 vpngate 목록 조회불가 버그)는 해결했습니다.

**Comment by LiteHell** [comment]
180422.0 버전에서 해결
