### ISSUE TITLE
아카이브 오류

### ISSUE THREAD

**Issue by wodud98** [LiteHell/NamuFix#93]
# 설명
버그나 추가를 요청하실 사항이나 질문등의 내용들을 자유롭게, 그리고 최대한 자세하게 여기에 써주세요.

# 이용환경
 * 운영체제 : Windows 7 / Android 4.4 와 같이 써주세요. (필수)
 * 브라우저 : Firefox  / Chrome  와 같이 써주세요. (필수)
 * 사용하는 유저스크립트 매니저 : Tampermonkey 와 같이 NamuFix를 구동하는 유저스크립트 확장을 써주세요. (필수)
 * 함께 이용하는 확장 : 나무위키에서 동작하는 유저스크립트나 확장을 이용하신다면 써주세요. (권장)

원래 아카이브 하면 자동으로 넘어가던데 아카이브 페이지로 넘어가네요 사소한 버그인것 같은데 최근 패치되면서 그런것 같습니다.

**Comment by Hoto-Cocoa** [comment]
틀이 있으면 틀에 맞게 써주시기 바랍니다...

**Comment by LiteHell** [comment]
180507.0 버전에서 해결됨.
