### ISSUE TITLE
Liberty 스킨에서 SNS 공유 버튼이 깨지는 문제

### ISSUE THREAD

**Issue by System-K** [LiteHell/NamuFix#95]
# 설명
Liberty 스킨은 ionicons를 사용하지 않아서 Font Awesome으로 대체해야만 사용 가능. 근데 Font Awesome으로 대체하면 또 senkawa가 깨짐. 둘 다 지원하는 CSS를 사용해야 할 듯

# 이용환경
 * 운영체제 : Windows 10 Insider Preview (17661.1001)
 * 브라우저 : Chrome Beta 67.0.3396.30
 * 사용하는 유저스크립트 매니저 : Tampermonkey
 * 함께 이용하는 확장 : None

**Comment by LiteHell** [comment]
180519.0 버전에서 해결됨.
