### ISSUE TITLE
"마우스를 올리면 해당 사용자의 다른 쓰레 강조" 기능 개선

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#97]
# 설명
현재는 **마우스를 올려야 강조가 되는데**, **클릭(혹은 터치)하여 강조 상태를 유지/해제 할 수 있도록** 개선이 되면 좋을 것 같습니다.

# 이용환경
 * 운영체제 : Windows 10 RS4
 * 브라우저 : Chrome 66.0.3359.170(공식 빌드) (64비트)
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by LiteHell** [comment]
@pb1112 좋은 아이디어네요.

**Comment by pb1112** [comment]
이건 마개조 수준이 될것 같긴 한데

특정 사용자의 토론을 강조하면 다른 사용자의 스레드는 블러 처리? 되도 좋을것 같습니다.

**Comment by LiteHell** [comment]
@pb1112 흐려지는 걸 말씀하시는건가요?

**Comment by LiteHell** [comment]
@pb1112 학업때문에 늦을 수 있지만, 빠른 시일내에 개발할 수 있도록 노력하겠습니다.

**Comment by LiteHell** [comment]
180519.0 버전에서 해결됨.
