### ISSUE TITLE
문서의 역사 내에서 특정 사용자의 리비전 검색 기능 추가

### ISSUE THREAD

**Issue by pb1112** [LiteHell/NamuFix#99]
# 설명
문서의 역사 페이지내에서 특정 사용자의 리비전 검색을 할 수 있는 기능이 추가되면 좋을것 같습니다. 예를 들어 "Polarbear1112"를 검색하면 Polarbear1112 유저가 편집한 리비전만 강조 혹은 리스트로 표시되고 나머지는 안보이게 된다든지 말이죠.

만일 역사 로그 전체에서 불가능하다면, 보이는 한 페이지 에서만 검색이 가능해도 좋을것 같습니다.

# 이용환경
 * 운영체제 : Windows 10
 * 브라우저 : Vivaldi 1.15.1147.42 (Chrome 65.0.3325.183 기반)
 * 사용하는 유저스크립트 매니저 : Tampermonkey

**Comment by wodud98** [comment]
불러온 한 페이지에서만 작동한다면, 의미가 없지 않을까요... Ctrl + F 랑 동일한데....

**Comment by wodud98** [comment]
이 기능이 만약에 가능하다면, 이와 동시에 특정 문서에서 기여자 목록 전체를 불러올 수 있는 기능이 있으면 좋겠습니다.

**Comment by LiteHell** [comment]
@wodud98 특정 문서 기여자 목록 불러오는 건 사실상 불가능합니다. reCAPTCHA 마스터했다면 모를까...

**Comment by wodud98** [comment]
하기야 1000리비젼보려면 40번가까이 가져와야되니.... 그놈의 리캡차가 말썽을....

**Comment by pb1112** [comment]
그렇다면 이 기능도 불가능하다고 봐야 하나요?

**Comment by wodud98** [comment]
본관의 Ddos 방어(리캡차)에 대한 협조가 있으면 가능할 것 같습니다.

**Comment by LiteHell** [comment]
@wodud98 @wodud98 DDoS 방어 협조를 사측에 바랄바에 로또 인생역전을 바라겠습니다...

**Comment by Hoto-Cocoa** [comment]
reCAPTCHA는 DDoS 방어라기보다는 반달봇 방지에 가깝죠.

**Comment by Hoto-Cocoa** [comment]
reCAPTCHA를 자동으로 풀어주는 애가 있던데, 이걸 써도 되겠네요. 물론 사용자 or 개발자님이 돈을 내야겠지만요 ㅎㅎㅎ

**Comment by LiteHell** [comment]
@Hoto-Cocoa 아 그거 써봤는데 코딩하기가 귀찮음.

**Comment by Hoto-Cocoa** [comment]
@LiteHell 저런

**Comment by wodud98** [comment]
https://board.namu.wiki/qna/1087047 줄이긴 했다네요.
